spring:
  application:
    name: reward-service
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reward-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:reward-service}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:1}
      pool-name: ${SPRING_DATASOURCE_POOL_NAME:HikariPool}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

pyroscope:
  server:
    address: ${PYROSCOPE_SERVER_ADDRESS}
  auth:
    user: ${PYROSCOPE_AUTH_USER}
    password: ${PYROSCOPE_AUTH_PASSWORD}