name: Reward Service Build

on:
  push:
    branches:
      - main
    paths:
      - 'reward-service/**'  # Only trigger when changes are made to the reward-service
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build and Test Reward Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./reward-service  # Set default working directory to reward-service
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Use full history for better analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Verify Java Version
        run: java --version

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Make mvnw Executable
        run: chmod +x ./mvnw

      - name: Build and Test Reward Service
        run: ./mvnw clean verify jacoco:report

      - name: Debug Target Directory
        run: |
          echo "---- Listing target directory contents ----"
          ls -la target || echo "No target directory found."
          
          if [ -d "target/site/jacoco" ]; then
            echo "---- Listing JaCoCo reports ----"
            ls -la target/site/jacoco
          else
            echo "No JaCoCo reports found."
            mkdir -p target/site/jacoco
          fi

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: reward-service-coverage
          path: reward-service/target/site/jacoco/*
          if-no-files-found: warn

      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: >
          ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=Reward-Service-Check
          -Dsonar.projectName="Reward Service"
          -Dsonar.java.coveragePlugin=jacoco
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
